### ISSUE TITLE
documentation examples

### ISSUE THREAD

**Issue by corybrunson** [fauvernierma/survPen#14]
As noted in #9 the documentation is impressive. Regarding the exported documentation (for `help()`), the primary five functions (`survPen()` and the spline constructors) include several examples, but most of the helper functions (by which i mean, all other functions) do not. And many of these functions rely on a deep understanding of the package internals to understand and test.

This leads me to ask: Is the helper function documentation intended for developers or for users? If for developers, then should it be exported? If for users, then should examples not be included?

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/1434)._

**Comment by fauvernierma** [comment]
Hi,

I understand your point. As for me, it felt important that all functions are exported so the users can get a bit of information. However, as you noted most functions do not have examples because I felt it was pointless to give any (as these functions will never get called directly by the users).

Honestly I am not sure what is best: not to export all functions or add examples for all functions ?

Could it possibly stay as is (like a compromise between the two)

Do you or @seabbs have a preference ? 

Thanks

**Comment by corybrunson** [comment]
I just have a preference for exported functions to include examples. ; ) I think i see where you're coming from, but to my mind a user gains little from having access to a function if the behavior of that function is cannot be validated (as against an example). Put another way: Presumably you can imagine a user using these functions directly for some reason. Whatever that reason, could you include an example of it?

Perhaps this is more true for some of the helper functions than others, so perhaps only those few would benefit from examples. I can take another close look in a few days if you'd like more specific feedback—it's not fresh in my mind and i don't have the time this weekend! And i also welcome thoughts from @seabbs.

**Comment by seabbs** [comment]
I completely agree with @corybrunson.

 Personally, I think everything should have an example unless there is a clear reason for it not to. This helps users understand the workings of each function in the package rather than treating it as a complete black box.

A benefit of having examples for each function is that they can relatively easily be converted into meaningful tests. The tests as currently stands are mostly checking the class of objects and this would go a long way to improving them.

**Comment by fauvernierma** [comment]
I added examples 086e829433695a0cbd28c9d9f72099a610c2d327 for all functions but three of them (inv.repam, cor.var and print.summary, these three are therefore not exported any longer)

**Comment by seabbs** [comment]
Great. It would be good to see full comments as far as possible. 

I am not sure but I think you can skip loading `survPen` in every example.

**Comment by fauvernierma** [comment]
ok thanks

I would rather keep the loading part as I often forget to load it myself :) 
I think it is convenient to be able to copy and paste it for every example but I do not know if it is good practice

**Comment by fauvernierma** [comment]
I just added some comments for each example 70c43f44cc8329c3541f95d8578cc74c1f705d5f

**Comment by seabbs** [comment]
Great - nice work. These all look good to me. Happy to close if @corybrunson agrees.

**Comment by corybrunson** [comment]
@fauvernierma could you update the package documentation? The new examples don't appear there yet.

**Comment by fauvernierma** [comment]
Yes, sorry about that, it is ok now eadbb0a92e33ccf9b488dba52ed45456c3f6e692

**Comment by corybrunson** [comment]
Yes, they're showing up now. Thanks!

I ran into at least one problem, though, in the `model.cons()` example that also appears as a test:

``` r
library(survPen)

data <- data.frame(time=seq(0,5,length=100),event=1,t0=0)

form <- ~ smf(time,knots=c(0,1,3,5))

t1 <- eval(substitute(time), data)
t0 <- eval(substitute(t0), data)
event <- eval(substitute(event), data)

model.c <- model.cons(form,lambda=0,data.spec=data,t1=t1,t1.name="time",
                      t0=rep(0,100),t0.name="t0",event=event,event.name="event",
                      expected=NULL,expected.name=NULL,type="overall",n.legendre=20,cl="survPen(form,data,t1=time,event=event)")
#> Error in model.cons(form, lambda = 0, data.spec = data, t1 = t1, t1.name = "time", : dims [product 400] do not match the length of object [0]
```

<sup>Created on 2019-07-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Does this run successfully for others?

(To caveat, i've been running the code on R v3.3.3, so i've changed `DESCRIPTION` locally to allow installation. I doubt that's the issue, but i mention it just in case.)

**Comment by fauvernierma** [comment]
There is no problem for me with R version >= 4.0.0 so I guess version could be an issue here

**Comment by fauvernierma** [comment]
ok

The "expected" argument should not be NULL here but "rep(0,100)". Otherwise, at the end of the function model.cons, the following expression (line 1979 of the survPen code)

eventXexpected <- eventX*expected

returns an error. R version < 4.0.0 does not accept the multiplication between a matrix and a NULL whereas R version >=4.0.0 accepts this

**Comment by fauvernierma** [comment]
This should be ok now a58768bdcd4e99bf7dbb32bdd21fa981f818e111

**Comment by fauvernierma** [comment]
To support my explanation see 
https://cran.r-project.org/bin/windows/base/old/3.4.0/NEWS.R-3.4.0.html

"In integer arithmetic, NULL is now treated as integer(0) whereas it was previously treated as double(0)."

**Comment by corybrunson** [comment]
Aha, OK, then not only does the example work, but the default value `expected = NULL` is appropriate for R `v>=3.4.0`. Since this is a key point, i would suggest leaving `expected = NULL` in the test but changing it to `expected = rep(0, 100)` in the example. Or, to make the package more backward-compatible, the function could be amended to handle `expected = NULL` more explicitly. But that's not a requirement! The issue with `model.cons()` is basically resolved.

I also haven't come across any other problems with the examples or tests, so, since i opened this issue (and since @seabbs has given the go-ahead), i'll close it. Thanks for addressing these questions @fauvernierma !
